/Users/rahulshetty/Pantheon_code/hash_trackerv2/data/collector.log {
    daily
    rotate 7
    compress
    missingok
    notifempty
    copytruncate
}

/Users/rahulshetty/Pantheon_code/hash_trackerv2/data/dht_peer.log {
    daily
    rotate 7
    compress
    missingok
    notifempty
    copytruncate
}
